final List<String> finalFrases = [
  'Relaxa, vai adivinhar essa',
  'Pense com calma...',
  'Ta difícil?',
  'Ei, se concentre!',
  'Eu sabia essa com laranjas...',
  'Essa é fácil, manda outra',
  'Complicado, não?',
  'Responda se for capaz',
  'Você está quase lá... Ou não.',
  'Não desista agora! A menos que queira.',
  'Vamos lá, uma dica: respire fundo e tente não sufocar.',
  'Concentre-se, ou não. Não estou julgando.',
  'Está no caminho certo! Ou talvez não.',
  'Quase alcançou a resposta! Ou não.',
  'É normal ter dificuldades, mas para alguns, é mais normal ainda.',
  'Você consegue, só mais um pouco! Ou talvez não.',
  'Não perca a esperança, mas não garanto nada.',
  'Continue pensando, a resposta está próxima... Ou não.',
  'A persistência é a chave para o sucesso, ou é o bloqueio?',
  'Não se apresse, ou se apresse. Eu não ligo.',
  'A resposta está à sua frente, ou não. Vai saber.',
  'Você está quase lá, mantenha o foco... Ou perca-o completamente.',
  'Acredite em si mesmo, ou não. Quem se importa?',
  'Você está no caminho certo, ou não. Quem sabe?',
  'Você vai conseguir, ou não. Que diferença faz?',
  'Pensar é altamente subjetivo. Ou não?',
  'Se a resposta fosse dinheiro, você seria um bilionário... Ou não.'
];
